apiVersion: v1
kind: ConfigMap
metadata:
  name: synergychat-crawler-configmap   # ðŸ‘ˆ must match deployment
data:
  CRAWLER_PORT: "8080"
  CRAWLER_KEYWORDS: love,hate,joy,sadness,anger,disgust,fear,surprise
